#!/bin/sh

sessionupgrade() {
	if [ -e "/usr/bin/phosh-session.real" ]; then
		rm -f "/usr/bin/phosh-session"
		dpkg-divert \
			--rename \
			--package phosh-config-hwcomposer \
			--divert /usr/bin/phosh-session.real \
			--remove /usr/bin/phosh-session
	fi
}

remove() {
	rm -f /etc/systemd/system/phosh.service.d/90-force-legacy-user.conf
}

case "$1" in
	"remove")
		sessionupgrade
		remove
		;;
esac
